config/routes.rb
Rails.application.routes.draw do
  resources :courses
  devise_for :users
  resources :subscriptions, only: :create do
    collection do
      get :my_subscriptions
    end
  end

  get :my_courses , to: "instructors#my_courses", as: :my_courses
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "courses#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    can :manage, :all if user.admin?
    can :read, Course
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :instructor, class_name: "User", foreign_key: "instructor_id"
  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions, dependent: :destroy
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  enum role: [:student, :instructor, :admin]

  after_initialize :set_default_role, if: :new_record?

  scope :instructors, -> { where(:role => "instructor")}

  has_many :subscriptions, dependent: :destroy
  has_many :courses, through: :subscriptions, dependent: :destroy
  has_many :instructor_courses, class_name: "Course", foreign_key: :instructor_id, dependent: :destroy

  private

  def set_default_role
    self.role ||= :student
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to root_path, alert: exception.message }
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  load_and_authorize_resource
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    @courses = if params[:search].present?
      Course.where("LOWER(title) LIKE ?", "%#{params[:search].downcase}%")
    else
      Course.all
    end
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to course_url(@course), notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to course_url(@course), notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy!

    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:title, :description, :instructor_id, :duration, :price, :start_date, :end_date, :course_type)
    end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  def my_courses
    @my_courses = current_user.instructor_courses
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def create
    subscription = Subscription.find_or_initialize_by(course_id: params[:course_id])
    subscription.total_price = subscription.course.price
    subscription.user  = current_user
    subscription.save

    redirect_to my_subscriptions_subscriptions_path
  end

  def my_subscriptions
    @my_subscriptions = current_user.courses
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/courses/_course.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <div id="<%= dom_id course %>">
      <p>
        <strong>Title:</strong>
        <%= link_to course.title, course_path(course), class: "card-link text-decoration-none" %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= course.description %>
      </p>

      <p>
        <strong>Instructor:</strong>
        <%= course.instructor.name %>
      </p>

      <p>
        <strong>Duration:</strong>
        <%= course.duration %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= course.price %>
      </p>

      <p>
        <strong>Start date:</strong>
        <%= course.start_date %>
      </p>

      <p>
        <strong>End date:</strong>
        <%= course.end_date %>
      </p>

      <p>
        <strong>Course type:</strong>
        <%= course.course_type %>
      </p>
    </div>
    <% if current_user.subscriptions.where(course_id: course.id).present? %>
      <span class="btn btn-success">Subscribed</span>
    <% else %>
      <%= link_to "Subscribe Now", subscriptions_path(course_id: course ), data: { turbo_method: :post }, class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :instructor_id, style: "display: block" %>
    <%= form.collection_select :instructor_id, User.instructors, :id, :name, prompt: "Select User" %>
  </div>

  <div>
    <%= form.label :duration, style: "display: block" %>
    <%= form.text_field :duration %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.date_field :start_date %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :course_type, style: "display: block" %>
    <%= form.text_field :course_type %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Show this course", @course %> |
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Courses</h1>

  <% if can? :manage, Course %>
    <%= link_to "New course", new_course_path, class: "btn btn-primary my-4" %>
  <% end %>

  <div id="courses", class="row d-flex">
    <% @courses.each do |course| %>
      <div class="col-3 mt-4">
        <%= render course %>
      </div>
    <% end %>
  </div>
</div>

app/views/courses/new.html.erb
<h1>New course</h1>

<%= render "form", course: @course %>

<br>

<div>
  <%= link_to "Back to courses", courses_path %>
</div>

app/views/courses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @course %>

<% if current_user.instructor? or current_user.admin? %>
  <div class="my-3">
    <h2>Users list</h2>
    <ul>
      <% @course.users.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div>
  <%= link_to "Back to courses", courses_path %>
   <% if can? :manage, Course %>
    <%= link_to "Edit this course", edit_course_path(@course) %> |

    <%= button_to "Destroy this course", @course, method: :delete %>
  <% end %>
</div>

app/views/instructors/my_courses.html.erb
<div id="courses", class="row d-flex">
  <% @my_courses.each do |course| %>
    <div class="col-3 mt-4">
      <%= render course %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseOfferingManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <p class="navbar-text float-right">
    <%= link_to "Home", courses_path, class: "navbar-link"  %>
    <% course_path =  current_user&.student? ? my_subscriptions_subscriptions_path : my_courses_path %>
    <%= link_to "My Courses", course_path, class: "navbar-link"  %>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to "Edit profile", edit_user_registration_path, class: "navbar-link" %> |
      <%= link_to "Logout", destroy_user_session_path,  data: { turbo_method: :delete }, class: "navbar-link"  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-link"  %> |
      <%= link_to "Login", new_user_session_path, class: "navbar-link"  %>
    <% end %>
    </p>

    <%= form_tag(courses_path, :method => "get", class: 'navbar-form navbar-left') do %>  
      <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %>  
        <div class="input-group-btn">  
          <%= button_tag "Search", :class => 'btn btn-primary glyphicon glyphicon-search', name: nil %>  
        </div> 
      </div>  
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/subscriptions/my_subscriptions.html.erb
<div id="courses", class="row d-flex">
  <% @my_subscriptions.each do |course| %>
    <div class="col-3 mt-4">
      <%= render course %>
    </div>
  <% end %>
</div>